version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 3
    versioning-strategy: increase
    rebase-strategy: 'disabled'
    commit-message:
      prefix: 'upgrade'
      prefix-development: 'upgrade'
      include: 'scope'
    groups:
      linting:
        applies-to: version-updates
        patterns:
        - "*eslint*"
        - "prettier"

        update-types:
        - 'major'
        - 'minor'
        - 'patch'
